const PRODUCTS_HAS_ERROR = "PRODUCTS_HAS_ERROR";
const PRODUCTS_IS_LOADING = "PRODUCTS_IS_LOADING";
const PRODUCTS_FETCH_DATA_SUCCESS = "PRODUCTS_FETCH_DATA_SUCCESS";
const PRODUCTS_FILTER = "PRODUCTS_FILTER";
const SEARCH = "SEARCH";

export default {
  PRODUCTS_HAS_ERROR,
  PRODUCTS_IS_LOADING,
  PRODUCTS_FETCH_DATA_SUCCESS,
  PRODUCTS_FILTER,
  SEARCH
};
