const THREAD_HAS_ERROR = "THREAD_HAS_ERROR";
const THREAD_IS_LOADING = "THREAD_IS_LOADING";
const THREAD_FETCH_DATA_SUCCESS = "THREAD_FETCH_DATA_SUCCESS";
const THREAD_POST_DATA_SUCCESS = "THREAD_POST_DATA_SUCCESS";

export default {
  THREAD_HAS_ERROR,
  THREAD_IS_LOADING,
  THREAD_FETCH_DATA_SUCCESS,
  THREAD_POST_DATA_SUCCESS
};
