const REPRESENTATIVES_HAS_ERROR = "REPRESENTATIVES_HAS_ERROR";
const REPRESENTATIVES_IS_LOADING = "REPRESENTATIVES_IS_LOADING";
const REPRESENTATIVES_FETCH_DATA_SUCCESS = "REPRESENTATIVES_FETCH_DATA_SUCCESS";

export default {
  REPRESENTATIVES_HAS_ERROR,
  REPRESENTATIVES_IS_LOADING,
  REPRESENTATIVES_FETCH_DATA_SUCCESS
};
