const RATINGS_HAS_ERROR = "RATINGS_HAS_ERROR";
const RATINGS_IS_LOADING = "RATINGS_IS_LOADING";
const RATINGS_FETCH_DATA_SUCCESS = "RATINGS_FETCH_DATA_SUCCESS";

export default {
	RATINGS_HAS_ERROR,
	RATINGS_IS_LOADING,
	RATINGS_FETCH_DATA_SUCCESS
};
