const RATING_FETCH_DATA_SUCCESS = "RATING_FETCH_DATA_SUCCESS";
const RATING_FETCH_DATA_ERROR = "RATING_FETCH_DATA_ERROR";
const RATING_POST_DATA_SUCCESS = "RATING_POST_DATA_SUCCESS";

export default {
	RATING_FETCH_DATA_SUCCESS,
	RATING_FETCH_DATA_ERROR,
	RATING_POST_DATA_SUCCESS
};
