const RATING_FETCH_DATA_SUCCESS = "RATING_FETCH_DATA_SUCCESS";
const RATING_HAS_ERROR = "RATING_HAS_ERROR";
const RATING_POST_DATA_SUCCESS = "RATING_POST_DATA_SUCCESS";

export default {
	RATING_FETCH_DATA_SUCCESS,
	RATING_HAS_ERROR,
	RATING_POST_DATA_SUCCESS
};
