const CATEGORIES_HAS_ERROR = "CATEGORIES_HAS_ERROR";
const CATEGORIES_IS_LOADING = "CATEGORIES_IS_LOADING";
const CATEGORIES_FETCH_DATA_SUCCESS = "CATEGORIES_FETCH_DATA_SUCCESS";
const CATEGORIES_POST_DATA_SUCCESS = "CATEGORIES_POST_DATA_SUCCESS";

export default {
  CATEGORIES_HAS_ERROR,
  CATEGORIES_IS_LOADING,
  CATEGORIES_FETCH_DATA_SUCCESS,
  CATEGORIES_POST_DATA_SUCCESS
};
