const COMPANIES_HAS_ERROR = "COMPANIES_HAS_ERROR";
const COMPANIES_IS_LOADING = "COMPANIES_IS_LOADING";
const COMPANIES_FETCH_DATA_SUCCESS = "COMPANIES_FETCH_DATA_SUCCESS";

export default {
  COMPANIES_HAS_ERROR,
  COMPANIES_IS_LOADING,
  COMPANIES_FETCH_DATA_SUCCESS
};
