const FORUM_HAS_ERROR = "FORUM_HAS_ERROR";
const FORUM_IS_LOADING = "FORUM_IS_LOADING";
const FORUM_FETCH_DATA_SUCCESS = "FORUM_FETCH_DATA_SUCCESS";
const FORUM_POST_DATA_SUCCESS = "FORUM_POST_DATA_SUCCESS";

export default {
  FORUM_HAS_ERROR,
  FORUM_IS_LOADING,
  FORUM_FETCH_DATA_SUCCESS,
  FORUM_POST_DATA_SUCCESS
};
